/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_EMBEDDEDMESSAGES_GENERAL_INSTRUCTIONS_PB_H_INCLUDED
#define PB_EMBEDDEDMESSAGES_GENERAL_INSTRUCTIONS_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _GeneralInstructions_MainInstrEnum {
    GeneralInstructions_MainInstrEnum_DO_NOTHING = 0,
    GeneralInstructions_MainInstrEnum_REBOOT = 1,
    GeneralInstructions_MainInstrEnum_FREE_MEM = 2,
    GeneralInstructions_MainInstrEnum_FLASH_LED = 3
} GeneralInstructions_MainInstrEnum;

/* Struct definitions */
typedef struct _GeneralInstructions {
    GeneralInstructions_MainInstrEnum main_instructions;
} GeneralInstructions;


/* Helper constants for enums */
#define _GeneralInstructions_MainInstrEnum_MIN GeneralInstructions_MainInstrEnum_DO_NOTHING
#define _GeneralInstructions_MainInstrEnum_MAX GeneralInstructions_MainInstrEnum_FLASH_LED
#define _GeneralInstructions_MainInstrEnum_ARRAYSIZE ((GeneralInstructions_MainInstrEnum)(GeneralInstructions_MainInstrEnum_FLASH_LED+1))


/* Initializer values for message structs */
#define GeneralInstructions_init_default         {_GeneralInstructions_MainInstrEnum_MIN}
#define GeneralInstructions_init_zero            {_GeneralInstructions_MainInstrEnum_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define GeneralInstructions_main_instructions_tag 1

/* Struct field encoding specification for nanopb */
#define GeneralInstructions_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    main_instructions,   1)
#define GeneralInstructions_CALLBACK NULL
#define GeneralInstructions_DEFAULT NULL

extern const pb_msgdesc_t GeneralInstructions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GeneralInstructions_fields &GeneralInstructions_msg

/* Maximum encoded size of messages (where known) */
#define GeneralInstructions_size                 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
